'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ScreeningSuccess

    '''<summary>
    '''fvScreenedPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvScreenedPerson As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''hidScreenedPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidScreenedPersonID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''divCompChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCompChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnAppInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAppInstructions As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSendInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SqlScreenedPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlScreenedPerson As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''hidStateProv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidStateProv As Global.System.Web.UI.WebControls.HiddenField
End Class
